### ISSUE TITLE
Implement existing facial features

### ISSUE THREAD

**Issue by JeanCHilger** [JeanCHilger/readminds-features-study#13]
#14 is required

### Deadline\*: 05/12/2020.

Based on the exploration of the face mesh functionality (#10), the already existing facial features must be implemented using MediaPipe. Thus, features `F1` to `F7` will be reimplemented.

**\*Note:** We should try to end this issue at 3rd December, when we'll meet with swedish team.

**Comment by arufonsekun** [comment]
Features `F1` - `F7` can be found in this [paper](http://downloads.hindawi.com/journals/ijcgt/2018/8734540.pdf).

**Comment by Dovyski** [comment]
You might also want to check the C++ implementation of such paper available [here](https://github.com/Dovyski/readminds/tree/master/src/main-app/face/analysis).

**Comment by JeanCHilger** [comment]
Deadline was changed to **07/12/2020** due to planning issues.

**Comment by JeanCHilger** [comment]
Implementations:

@arufonsekun: `F3`, `F4`, `F7`;
@JeanCHilger: `F1`, `F2`, `F5`;

Feature `F6` will be later implemented.

**Comment by JeanCHilger** [comment]
I'll be implementing feature `F6`.
