### ISSUE TITLE
Get mappings from landmark points to features

### ISSUE THREAD

**Issue by JeanCHilger** [JeanCHilger/readminds-features-study#14]
#10 is required;

### Deadline: 02/12/2020.

In order to implement these features we need to know in advance what are the landmark points related (and relevant) to them. Thus, using the images (within `data/faces/`) produced in issue #10, we must first identify such points. The division (generated by a random algorithm) of who gets which feature mapping is the following:

- @arufonsekun: `F3` and `F7`;
- @jeanchilger: `F5` and `F6`;
- @henriqueherrera: `F2` and `F4`;

The feature `F1` was left aside, so the first to finish their mapping gets it.

The objective of this stage is to obtain all the landmark points related to each feature.

All the mappings should be reported on the document shared. Later, it will be better developed into a formal report.

**Comment by arufonsekun** [comment]
In Fernando's paper each feature `F` is divided by a coefficient `K`  which is the nose line size, I guess We should define 2 points in the Mediapipe face mesh implementation (there are several to choose) then We can compute `K` and implement the same strategy as Fernando did.

**Comment by arufonsekun** [comment]
My suggestion is to use  `168` or `6` as upper nose landmark and `1` or `2` as lower, however it depends on whether We want a nose line similar to the original (described by the paper) or a more accurate one.

**Comment by JeanCHilger** [comment]
I guess `2` and `168` would be a good choice. Here I've drawn the nose line for them:

![image](https://user-images.githubusercontent.com/19687197/100761282-7c359580-33d1-11eb-81ae-f07c154f8218.png)

**Comment by JeanCHilger** [comment]
I've set the anchor as the points `4`, `5` and `195` (check the document), maybe `197` included. From `4` to `195` we would have this:

![image](https://user-images.githubusercontent.com/19687197/100761953-3af1b580-33d2-11eb-8bd1-ad3460250190.png)

Maybe to small. In paper, the anchor and `K` share the same points, we might use such a approach, or we could use separate points for both?

**Comment by JeanCHilger** [comment]
Using `1` and `6` seems good to:

![image](https://user-images.githubusercontent.com/19687197/100762445-ba7f8480-33d2-11eb-918d-672091987102.png)

**Comment by JeanCHilger** [comment]
@Dovyski which one, among the three, you think would do better the job?

**Comment by Dovyski** [comment]
I've used 3 points in the original features because I did not have this much landmarks to choose from. Judging by the images, I think using `1` and `5` looks more "stable" (landmark `6` seems to be affected by mouth movement, which is not good for anchors).

**Comment by JeanCHilger** [comment]
Since our deadline has passed, I'll be performing the mappings for `F2` and `F4`, that are not ready yet.

**Comment by JeanCHilger** [comment]
Mapping finished, issue will be closed.
