### ISSUE TITLE
[Report] Produce Report I

### ISSUE THREAD

**Issue by jeanchilger** [jeanchilger/readminds-features-study#16]
**Deadline:** 08/01/2020.

The report should discuss the following topics:

- [x] **1.** Thesis overview, explaining our part of the problem;
  - [x] **1.1** Focus on the part about emotions;
- [x] **2.** Explain the process of reimplementing the facial features;

Other relevant topics should be argued on this issue.

**Note:** We may start this report by December 26th.

**Comment by JeanCHilger** [comment]
We must cite [this paper](https://downloads.hindawi.com/journals/ijcgt/2018/8734540.pdf) and [Fernando's thesis](http://his.diva-portal.org/smash/record.jsf?pid=diva2%3A1259426&dswid=5024). More references may be used as well, but these two are the core.

**Comment by jeanchilger** [comment]
This issue is obsolete. We'll provide comparative results between both "feature approaches" besides the listed subjects.
