### ISSUE TITLE
Implement ICA method for remote photoplethysmography (rPPG)

### ISSUE THREAD

**Issue by jeanchilger** [jeanchilger/readminds-features-study#20]
ICA remote photoplethysmography method - by Poh, M. Z., McDuff, D. J., & Picard, R. W. (2010), available at [github.com/phuselab/pyVHR](https://github.com/phuselab/pyVHR), should be implemented. Later, we'll expand implementation to benchmark all available methods.

**Comment by arufonsekun** [comment]
I'm working on it
