### ISSUE TITLE
Implement experiments for comparison between features

### ISSUE THREAD

**Issue by jeanchilger** [jeanchilger/readminds-features-study#25]
**Deadline: 30/01/2021.** 

The experiments will be executed using a helper program (preferably a CLI-like). This program must provide following functionalities:
1. It must accept an argument for number of executions that will be computed (e.g. we'll run the algorithms `N` times and compute the final result as the mean of the `N` individual results taken);
2. It must save both individual results for each execution performed and the final result;

**Comment by JeanCHilger** [comment]
Any additional functionality that might be useful, please comment on the issue.

**Comment by JeanCHilger** [comment]
**NOTE:** This script must control the model (passing appropriate parameters) and provide means to have a controlled experiment environment. [Sacred](https://github.com/IDSIA/sacred) framework might be useful.

**Comment by jeanchilger** [comment]
Would be nice to have #27 finished before, bus we will be testing the model mostly. Features extractors should be independent from this experiment, right?

**Comment by jeanchilger** [comment]
This issue will be delayed by a day, unfortunately.
